baseurl = "http://o.iee.io/"
title = "欢迎访问 EE.SUDA courses"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"
hasCJKLanguage = true
defaultContentLanguage = "zh"

[params]
  editURL = "https://github.com/su-da/website/edit/master/content/"
  description = "EE.SUDA courses"
  author = "Soochow University"
# Disable search function. It will hide search bar
  disableSearch = true
